### ISSUE TITLE
Confusion around official github page

### ISSUE THREAD

**Issue by MichaelAquilina** [taichino/croniter#125] opened 2019-03-28 17:26 UTC
It's hard to understand which is the official github page for this project right now

https://github.com/taichino/croniter seems like the original 
but https://github.com/kiorky/croniter is the one that contains the latest actual releases

Could you please provide clarity on this?

In the situation the main project is no longer the official source of truth, perhaps we can add a statement the README to provide some clarity?

**Comment by pkondainmar** [comment] 2019-03-28 17:31
True. Was about to raise the same. Earlier when I installed 0.3.27 got installed. But today itself that version missed and it is showing 0.3.29. 

Can you streamline a bit more, please?

**Comment by kiorky** [comment] 2019-03-28 22:25
It's because @taichino was the original maintainer, but i maintain croniter on my personal repo for ages now (10 years ? ;-)). All is synced between the two repos except for the tags where my repo is the source of thruth. As i do the release dance from my repo, that's why tags are pushed onto it.

I think that i will just resync tags as well to remove that inconsistency and adapt the release procedure.

If you have landed here, it's fine, you are in the good place, so nothing to add to the README :).

For 0.3.27 & 0.3.29, i wont repeat my self, see: https://github.com/taichino/croniter/issues/124#issuecomment-477209088


I close this as this is a discussion and not a bug, but we can continue if you have more comments.

**Closed by kiorky** 2019-03-28 22:25 UTC

**Comment by kiorky** [comment] 2019-03-28 22:28
tags are pushed also to @taichino repo (this one) now.
